chore(updatecli): don't hide `uplink` Docker image tag
jenkins-infra/helm-charts pull request #903
Opened 2023-10-30 14:20 UTC by lemeurherve

Exemple of PR where the (new) tag isn't visible: #899

2023-10-30 14:22 UTC, lemeurherve commented on updatecli/updatecli.d/uplink.yaml
>        - trimprefix: '@sha256:'
```suggestion
```

2023-10-30 14:33 UTC, dduportal requested changes

2023-10-30 14:33 UTC, dduportal commented on charts/uplink/values.yaml
> +  tag: 0.0.2@sha256:e57f1ee08d37c985388ebc87aafd3e7a73ad0a1a950abc1d2eb00c093eb3e76b
That will fail, resulting in the image `jenkinsciinfra/uplink@sha256:0.0.2@sha256:e57f1ee08d37c985388ebc87aafd3e7a73ad0a1a950abc1d2eb00c093eb3e76b` being checked (which is invalid).

2023-10-31 14:17 UTC, dduportal approved these changes

2023-10-31 14:22 UTC, merged